//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreDBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book()
        {
            this.Purchase_detail = new HashSet<Purchase_detail>();
            this.Sale_detail = new HashSet<Sale_detail>();
            this.Stocks = new HashSet<Stock>();
            this.Flash_sale = new HashSet<Flash_sale>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int Number_of_page { get; set; }
        public string Description { get; set; }
        public int Category_id { get; set; }
        public int Author_id { get; set; }
        public int Publisher_id { get; set; }
        public Nullable<decimal> Selling_price { get; set; }
        public Nullable<decimal> Cost_price { get; set; }
        public string Barcode { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual Category Category { get; set; }
        public virtual Publisher Publisher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchase_detail> Purchase_detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale_detail> Sale_detail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Stock> Stocks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Flash_sale> Flash_sale { get; set; }
    }
}
