//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStoreDBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase_order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Purchase_order()
        {
            this.Purchase_detail = new HashSet<Purchase_detail>();
        }
    
        public int Id { get; set; }
        public decimal Total_price { get; set; }
        public decimal Total_paid { get; set; }
        public decimal Total_remain { get; set; }
        public int Employee_id { get; set; }
        public int Supplier_id { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Supplier Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Purchase_detail> Purchase_detail { get; set; }
    }
}
